### ISSUE TITLE
Tab switching breaks when many tabs closed at once

### ISSUE THREAD

**Issue by FoxsDenYT** [FoxsDenYT/Flame-Next#3]
# Tab switching breaks when many tabs closed at once
## Steps to reproduce
1. Make lots of tabs
2. Close them quickly
3. Make more tabs
4. Then you cannot switch tabs
### Inspector Console
``` js
Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener')
    at changeTab (renderer.js:172:43)
    at addTab (renderer.js:45:5)
    at HTMLButtonElement.onclick (index.html:29:109)
```
#### Line(s) refrenced
```js 
document.querySelector(currentWebView).removeEventListener("did-navigate", webNavigated)
```
#### Error explanations (if appliable)
The currentWebView variable is not being updated, and this is shown through console.logs saying `#wbv8` the whole time
## Fixes
Line 13 changed from:
``` js
var currentWebView = "#wbv2"
```
to:
``` js
var currentWebView = "#wbv1"
```
---
On line 43, remove onclick attribute and move tab change to ln 44 and make it refrence the id of the tab
``` js
addthistab.onclick = "changeTab('"+addthistab.id+"')"
```

**Comment by FoxsDenYT** [comment]
wowwee that took so long to write

**Comment by FoxsDenYT** [comment]
Closing because fixed
